export const DEFAULT_DEVICE_BRANDS = [
  "HP",
  "Dell",
  "Lenovo",
  "Asus",
  "Acer",
  "Toshiba",
  "Apple",
  "MSI",
  "Samsung",
  "Xiaomi",
  "Huawei",
  "LG",
  "ViewSonic",
  "AOC",
];

export const DEFAULT_DEVICE_MODELS: Array<{
  brand: string;
  name: string;
  defaultSpecs: Record<string, string>;
}> = [
  { brand: "HP", name: "EliteBook 840 G5", defaultSpecs: { cpu: "Intel Core i5-8250U", ram: "8GB DDR4", storage: "256GB SSD", screenSize: "14\" FHD", gpu: "Intel UHD Graphics 620" } },
  { brand: "HP", name: "EliteBook 840 G7", defaultSpecs: { cpu: "Intel Core i5-10210U", ram: "8GB DDR4", storage: "256GB SSD", screenSize: "14\" FHD", gpu: "Intel UHD Graphics" } },
  { brand: "HP", name: "EliteBook 850 G8", defaultSpecs: { cpu: "Intel Core i7-1165G7", ram: "16GB DDR4", storage: "512GB SSD", screenSize: "15.6\" FHD", gpu: "Intel Iris Xe" } },
  { brand: "HP", name: "ProBook 450 G8", defaultSpecs: { cpu: "Intel Core i5-1135G7", ram: "8GB DDR4", storage: "256GB SSD", screenSize: "15.6\" FHD", gpu: "Intel Iris Xe" } },
  { brand: "HP", name: "Pavilion 15", defaultSpecs: { cpu: "Intel Core i5-1135G7", ram: "8GB DDR4", storage: "512GB SSD", screenSize: "15.6\" FHD", gpu: "Intel Iris Xe" } },
  { brand: "HP", name: "OMEN 15", defaultSpecs: { cpu: "Intel Core i7-10750H", ram: "16GB DDR4", storage: "512GB SSD", screenSize: "15.6\" FHD 144Hz", gpu: "RTX 2060" } },

  { brand: "Dell", name: "Latitude E5470", defaultSpecs: { cpu: "Intel Core i5-6300U", ram: "8GB DDR4", storage: "256GB SSD", screenSize: "14\" FHD", gpu: "Intel HD Graphics 520" } },
  { brand: "Dell", name: "Latitude 5400", defaultSpecs: { cpu: "Intel Core i5-8265U", ram: "8GB DDR4", storage: "256GB SSD", screenSize: "14\" FHD", gpu: "Intel UHD Graphics 620" } },
  { brand: "Dell", name: "Latitude 5420", defaultSpecs: { cpu: "Intel Core i5-1135G7", ram: "8GB DDR4", storage: "256GB SSD", screenSize: "14\" FHD", gpu: "Intel Iris Xe" } },
  { brand: "Dell", name: "Latitude 7420", defaultSpecs: { cpu: "Intel Core i7-1185G7", ram: "16GB DDR4", storage: "512GB SSD", screenSize: "14\" FHD", gpu: "Intel Iris Xe" } },
  { brand: "Dell", name: "Inspiron 15 3000", defaultSpecs: { cpu: "Intel Core i3-1115G4", ram: "4GB DDR4", storage: "128GB SSD", screenSize: "15.6\" HD", gpu: "Intel UHD Graphics" } },
  { brand: "Dell", name: "Inspiron 15 5000", defaultSpecs: { cpu: "Intel Core i5-1135G7", ram: "8GB DDR4", storage: "256GB SSD", screenSize: "15.6\" FHD", gpu: "Intel Iris Xe" } },
  { brand: "Dell", name: "XPS 13 9310", defaultSpecs: { cpu: "Intel Core i7-1165G7", ram: "16GB LPDDR4x", storage: "512GB SSD", screenSize: "13.4\" FHD+", gpu: "Intel Iris Xe" } },

  { brand: "Lenovo", name: "ThinkPad T480", defaultSpecs: { cpu: "Intel Core i5-8350U", ram: "8GB DDR4", storage: "256GB SSD", screenSize: "14\" FHD", gpu: "Intel UHD Graphics 620" } },
  { brand: "Lenovo", name: "ThinkPad T490", defaultSpecs: { cpu: "Intel Core i5-8265U", ram: "8GB DDR4", storage: "256GB SSD", screenSize: "14\" FHD", gpu: "Intel UHD Graphics 620" } },
  { brand: "Lenovo", name: "ThinkPad X1 Carbon Gen 9", defaultSpecs: { cpu: "Intel Core i7-1165G7", ram: "16GB LPDDR4x", storage: "512GB SSD", screenSize: "14\" FHD", gpu: "Intel Iris Xe" } },
  { brand: "Lenovo", name: "ThinkPad T14 Gen 2", defaultSpecs: { cpu: "Intel Core i5-1135G7", ram: "8GB DDR4", storage: "256GB SSD", screenSize: "14\" FHD", gpu: "Intel Iris Xe" } },
  { brand: "Lenovo", name: "ThinkPad E15 Gen 3", defaultSpecs: { cpu: "AMD Ryzen 5 5500U", ram: "8GB DDR4", storage: "256GB SSD", screenSize: "15.6\" FHD", gpu: "AMD Radeon Graphics" } },
  { brand: "Lenovo", name: "IdeaPad 3 15", defaultSpecs: { cpu: "Intel Core i3-1115G4", ram: "4GB DDR4", storage: "128GB SSD", screenSize: "15.6\" HD", gpu: "Intel UHD Graphics" } },
  { brand: "Lenovo", name: "Legion 5", defaultSpecs: { cpu: "AMD Ryzen 7 5800H", ram: "16GB DDR4", storage: "512GB SSD", screenSize: "15.6\" FHD 165Hz", gpu: "RTX 3060" } },

  { brand: "Asus", name: "VivoBook 15", defaultSpecs: { cpu: "Intel Core i3-1115G4", ram: "4GB DDR4", storage: "128GB SSD", screenSize: "15.6\" FHD", gpu: "Intel UHD Graphics" } },
  { brand: "Asus", name: "VivoBook S15", defaultSpecs: { cpu: "Intel Core i5-1135G7", ram: "8GB DDR4", storage: "512GB SSD", screenSize: "15.6\" FHD", gpu: "Intel Iris Xe" } },
  { brand: "Asus", name: "ZenBook 14", defaultSpecs: { cpu: "Intel Core i7-1165G7", ram: "16GB LPDDR4x", storage: "512GB SSD", screenSize: "14\" FHD", gpu: "Intel Iris Xe" } },
  { brand: "Asus", name: "TUF Gaming A15", defaultSpecs: { cpu: "AMD Ryzen 7 5800H", ram: "16GB DDR4", storage: "512GB SSD", screenSize: "15.6\" FHD 144Hz", gpu: "RTX 3060" } },

  { brand: "Acer", name: "Aspire 3", defaultSpecs: { cpu: "Intel Core i3-1115G4", ram: "4GB DDR4", storage: "128GB SSD", screenSize: "15.6\" HD", gpu: "Intel UHD Graphics" } },
  { brand: "Acer", name: "Aspire 5", defaultSpecs: { cpu: "Intel Core i5-1135G7", ram: "8GB DDR4", storage: "256GB SSD", screenSize: "15.6\" FHD", gpu: "Intel Iris Xe" } },
  { brand: "Acer", name: "Swift 3", defaultSpecs: { cpu: "Intel Core i5-1135G7", ram: "8GB LPDDR4x", storage: "512GB SSD", screenSize: "14\" FHD", gpu: "Intel Iris Xe" } },
  { brand: "Acer", name: "Nitro 5", defaultSpecs: { cpu: "Intel Core i5-11400H", ram: "8GB DDR4", storage: "512GB SSD", screenSize: "15.6\" FHD 144Hz", gpu: "RTX 3050" } },

  { brand: "Apple", name: "MacBook Air M1", defaultSpecs: { cpu: "Apple M1", ram: "8GB", storage: "256GB SSD", screenSize: "13.3\" Retina", gpu: "Apple M1 GPU" } },
  { brand: "Apple", name: "MacBook Air M2", defaultSpecs: { cpu: "Apple M2", ram: "8GB", storage: "256GB SSD", screenSize: "13.6\" Liquid Retina", gpu: "Apple M2 GPU" } },
  { brand: "Apple", name: "MacBook Pro 13\" M1", defaultSpecs: { cpu: "Apple M1", ram: "8GB", storage: "256GB SSD", screenSize: "13.3\" Retina", gpu: "Apple M1 GPU" } },
  { brand: "Apple", name: "MacBook Pro 14\" M1 Pro", defaultSpecs: { cpu: "Apple M1 Pro", ram: "16GB", storage: "512GB SSD", screenSize: "14.2\" Liquid Retina XDR", gpu: "Apple M1 Pro GPU" } },

  { brand: "MSI", name: "Modern 14", defaultSpecs: { cpu: "Intel Core i5-1135G7", ram: "8GB DDR4", storage: "512GB SSD", screenSize: "14\" FHD", gpu: "Intel Iris Xe" } },
  { brand: "MSI", name: "GF63 Thin", defaultSpecs: { cpu: "Intel Core i5-11400H", ram: "8GB DDR4", storage: "512GB SSD", screenSize: "15.6\" FHD", gpu: "GTX 1650" } },

  { brand: "Samsung", name: "Galaxy A12", defaultSpecs: { ram: "4GB", storage: "64GB", screenSize: "6.5\"", os: "Android" } },
  { brand: "Samsung", name: "Galaxy A14", defaultSpecs: { ram: "4GB", storage: "128GB", screenSize: "6.6\"", os: "Android" } },
  { brand: "Samsung", name: "Galaxy A15", defaultSpecs: { ram: "6GB", storage: "128GB", screenSize: "6.5\"", os: "Android" } },
  { brand: "Samsung", name: "Galaxy A32", defaultSpecs: { ram: "6GB", storage: "128GB", screenSize: "6.4\"", os: "Android" } },
  { brand: "Samsung", name: "Galaxy A52", defaultSpecs: { ram: "6GB", storage: "128GB", screenSize: "6.5\"", os: "Android" } },
  { brand: "Samsung", name: "Galaxy S21", defaultSpecs: { ram: "8GB", storage: "128GB", screenSize: "6.2\"", os: "Android" } },
  { brand: "Samsung", name: "Galaxy Tab A8", defaultSpecs: { ram: "4GB", storage: "64GB", screenSize: "10.5\"", os: "Android" } },
  { brand: "Samsung", name: "Galaxy Tab S6 Lite", defaultSpecs: { ram: "4GB", storage: "64GB", screenSize: "10.4\"", os: "Android" } },

  { brand: "Xiaomi", name: "Redmi Note 10", defaultSpecs: { ram: "4GB", storage: "128GB", screenSize: "6.43\"", os: "Android" } },
  { brand: "Xiaomi", name: "Redmi Note 11", defaultSpecs: { ram: "4GB", storage: "128GB", screenSize: "6.43\"", os: "Android" } },
  { brand: "Xiaomi", name: "Redmi Note 12", defaultSpecs: { ram: "6GB", storage: "128GB", screenSize: "6.67\"", os: "Android" } },
  { brand: "Xiaomi", name: "POCO X3 Pro", defaultSpecs: { ram: "6GB", storage: "128GB", screenSize: "6.67\"", os: "Android" } },

  { brand: "Huawei", name: "MateBook D14", defaultSpecs: { cpu: "AMD Ryzen 5 3500U", ram: "8GB DDR4", storage: "256GB SSD", screenSize: "14\" FHD", gpu: "AMD Radeon Graphics" } },
  { brand: "Huawei", name: "MatePad T10", defaultSpecs: { ram: "2GB", storage: "32GB", screenSize: "9.7\"", os: "Android" } },

  { brand: "LG", name: "24MK430H", defaultSpecs: { screenSize: "24\"", resolution: "1920x1080 (FHD)", panelType: "IPS" } },
  { brand: "ViewSonic", name: "VA2419-SH", defaultSpecs: { screenSize: "24\"", resolution: "1920x1080 (FHD)", panelType: "IPS" } },
  { brand: "AOC", name: "24B2XH", defaultSpecs: { screenSize: "24\"", resolution: "1920x1080 (FHD)", panelType: "IPS" } },
];

export const DEFAULT_PROCESSORS = [
  { name: "Intel Core i3-8130U", generation: "8th Gen" },
  { name: "Intel Core i3-1005G1", generation: "10th Gen" },
  { name: "Intel Core i3-1115G4", generation: "11th Gen" },
  { name: "Intel Core i5-6300U", generation: "6th Gen" },
  { name: "Intel Core i5-8250U", generation: "8th Gen" },
  { name: "Intel Core i5-8265U", generation: "8th Gen" },
  { name: "Intel Core i5-8350U", generation: "8th Gen" },
  { name: "Intel Core i5-10210U", generation: "10th Gen" },
  { name: "Intel Core i5-10300H", generation: "10th Gen" },
  { name: "Intel Core i5-1135G7", generation: "11th Gen" },
  { name: "Intel Core i5-11400H", generation: "11th Gen" },
  { name: "Intel Core i7-8550U", generation: "8th Gen" },
  { name: "Intel Core i7-10510U", generation: "10th Gen" },
  { name: "Intel Core i7-10750H", generation: "10th Gen" },
  { name: "Intel Core i7-1165G7", generation: "11th Gen" },
  { name: "Intel Core i7-1185G7", generation: "11th Gen" },
  { name: "Intel Core i7-11800H", generation: "11th Gen" },
  { name: "AMD Ryzen 3 3250U", generation: "Ryzen 3000" },
  { name: "AMD Ryzen 5 3500U", generation: "Ryzen 3000" },
  { name: "AMD Ryzen 5 4500U", generation: "Ryzen 4000" },
  { name: "AMD Ryzen 5 5500U", generation: "Ryzen 5000" },
  { name: "AMD Ryzen 5 5600H", generation: "Ryzen 5000" },
  { name: "AMD Ryzen 7 5700U", generation: "Ryzen 5000" },
  { name: "AMD Ryzen 7 5800H", generation: "Ryzen 5000" },
  { name: "Apple M1", generation: "M1" },
  { name: "Apple M1 Pro", generation: "M1" },
  { name: "Apple M2", generation: "M2" },
];

export const DEFAULT_RAM_OPTIONS = [
  { capacity: "2GB", type: "Generic" },
  { capacity: "4GB", type: "Generic" },
  { capacity: "6GB", type: "Generic" },
  { capacity: "8GB", type: "Generic" },
  { capacity: "12GB", type: "Generic" },
  { capacity: "16GB", type: "Generic" },
  { capacity: "4GB DDR4", type: "DDR4" },
  { capacity: "8GB DDR4", type: "DDR4" },
  { capacity: "16GB DDR4", type: "DDR4" },
  { capacity: "32GB DDR4", type: "DDR4" },
  { capacity: "8GB DDR5", type: "DDR5" },
  { capacity: "16GB DDR5", type: "DDR5" },
  { capacity: "32GB DDR5", type: "DDR5" },
  { capacity: "8GB LPDDR4x", type: "LPDDR4x" },
  { capacity: "16GB LPDDR4x", type: "LPDDR4x" },
  { capacity: "8GB (Apple)", type: "Unified" },
  { capacity: "16GB (Apple)", type: "Unified" },
];

export const DEFAULT_STORAGE_OPTIONS = [
  { capacity: "32GB", type: "Flash" },
  { capacity: "64GB", type: "Flash" },
  { capacity: "128GB", type: "Flash" },
  { capacity: "256GB", type: "Flash" },
  { capacity: "128GB SSD", type: "SSD" },
  { capacity: "256GB SSD", type: "SSD" },
  { capacity: "512GB SSD", type: "SSD" },
  { capacity: "1TB SSD", type: "SSD" },
  { capacity: "2TB SSD", type: "SSD" },
  { capacity: "128GB NVMe", type: "NVMe" },
  { capacity: "256GB NVMe", type: "NVMe" },
  { capacity: "512GB NVMe", type: "NVMe" },
  { capacity: "1TB NVMe", type: "NVMe" },
  { capacity: "500GB HDD", type: "HDD" },
  { capacity: "1TB HDD", type: "HDD" },
];

export const DEFAULT_SCREEN_SIZES = [
  { size: "6.2\"", resolution: "2400x1080 (FHD+)" },
  { size: "6.4\"", resolution: "2400x1080 (FHD+)" },
  { size: "6.5\"", resolution: "1600x720 (HD+)" },
  { size: "6.6\"", resolution: "2408x1080 (FHD+)" },
  { size: "6.67\"", resolution: "2400x1080 (FHD+)" },
  { size: "9.7\"", resolution: "1280x800 (HD)" },
  { size: "10.4\"", resolution: "2000x1200" },
  { size: "10.5\"", resolution: "1920x1200" },
  { size: "13.3\"", resolution: "1920x1080 (FHD)" },
  { size: "13.4\"", resolution: "1920x1200 (FHD+)" },
  { size: "13.6\"", resolution: "2560x1664 (Liquid Retina)" },
  { size: "14\"", resolution: "1920x1080 (FHD)" },
  { size: "14.2\"", resolution: "3024x1964 (Liquid Retina XDR)" },
  { size: "15.6\"", resolution: "1920x1080 (FHD)" },
  { size: "16.2\"", resolution: "3456x2234 (Liquid Retina XDR)" },
  { size: "17.3\"", resolution: "1920x1080 (FHD)" },
  { size: "24\"", resolution: "1920x1080 (FHD)" },
];
